apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    uid: postgres
    url: postgres:5432
    user: ${POSTGRES_USER}
    jsonData:
      database: ${POSTGRES_DB}
      sslmode: disable
      maxOpenConns: 5
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    editable: false
