const s = {
  root:        { display:'flex', height:'100vh', background:'#0f172a', color:'#f1f5f9', fontFamily:'system-ui,sans-serif', position:'relative', overflow:'hidden' },
  sidebar:     { width:'240px', display:'flex', flexDirection:'column', borderRight:'1px solid #1e293b', flexShrink:0 },
  sideTop:     { padding:'1rem', borderBottom:'1px solid #1e293b' },
  newBtn:      { width:'100%', padding:'0.6rem', borderRadius:'8px', background:'#6366f1', color:'#fff', border:'none', cursor:'pointer', fontWeight:600, fontSize:'0.875rem' },
  convList:    { flex:1, overflowY:'auto', padding:'0.5rem' },
  convItem:    { padding:'0.6rem 0.75rem', borderRadius:'8px', cursor:'pointer', marginBottom:'2px', fontSize:'0.8rem', lineHeight:1.4, position:'relative', display:'flex', justifyContent:'space-between', alignItems:'flex-start' },
  convMeta:    { flex:1, minWidth:0 },
  convTitle:   { display:'block', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis', color:'#cbd5e1' },
  convDate:    { display:'block', fontSize:'0.7rem', color:'#475569', marginTop:'2px' },
  convDel:     { flexShrink:0, marginLeft:'4px', marginTop:'1px', background:'none', border:'none', cursor:'pointer', color:'#475569', fontSize:'0.85rem', lineHeight:1, padding:'2px 4px', borderRadius:'4px' },

  chat:        { flex:1, display:'flex', flexDirection:'column', minWidth:0 },
  header:      { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'0.9rem 1.5rem', background:'#1e293b', borderBottom:'1px solid #334155' },
  title:       { fontWeight:700, fontSize:'1rem' },
  headerRight: { display:'flex', gap:'0.5rem', alignItems:'center' },
  hdrBtn:      { background:'none', border:'1px solid #334155', color:'#94a3b8', cursor:'pointer', padding:'0.3rem 0.75rem', borderRadius:'6px', fontSize:'0.8rem', display:'flex', alignItems:'center', gap:'0.35rem' },
  memDot:      { width:'6px', height:'6px', borderRadius:'50%', background:'#818cf8' },
  logout:      { background:'none', border:'1px solid #475569', color:'#94a3b8', cursor:'pointer', padding:'0.3rem 0.75rem', borderRadius:'6px', fontSize:'0.875rem' },

  feed:        { flex:1, overflowY:'auto', padding:'1.5rem', display:'flex', flexDirection:'column', gap:'1rem' },
  hint:        { color:'#475569', textAlign:'center', marginTop:'5rem', fontSize:'0.9rem' },
  bubble:      { maxWidth:'72%', padding:'0.75rem 1rem', borderRadius:'12px', lineHeight:1.55 },
  userBubble:  { alignSelf:'flex-end', background:'#6366f1' },
  aiBubble:    { alignSelf:'flex-start', background:'#1e293b', border:'1px solid #334155' },
  errBubble:   { alignSelf:'flex-start', background:'#450a0a', border:'1px solid #991b1b', color:'#fca5a5' },
  viewerOverlay: { position:'fixed', inset:0, background:'rgba(0,0,0,0.7)', zIndex:50, display:'flex', alignItems:'center', justifyContent:'center' },
  viewerModal:   { background:'#0f172a', border:'1px solid #1e293b', borderRadius:'12px', width:'700px', maxWidth:'95vw', maxHeight:'80vh', display:'flex', flexDirection:'column', boxShadow:'0 25px 50px rgba(0,0,0,0.5)' },
  viewerHeader:  { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'1rem 1.25rem', borderBottom:'1px solid #1e293b', flexShrink:0 },
  viewerTitle:   { fontSize:'0.9rem', fontWeight:600, color:'#e2e8f0', overflow:'hidden', textOverflow:'ellipsis', whiteSpace:'nowrap', flex:1, marginRight:'0.5rem' },
  viewerHdrRight:{ display:'flex', gap:'0.35rem', alignItems:'center', flexShrink:0 },
  viewerClose:   { background:'none', border:'none', color:'#64748b', cursor:'pointer', fontSize:'1.2rem', lineHeight:1, padding:'2px 6px', borderRadius:'4px' },
  viewerBody:    { flex:1, overflowY:'auto', padding:'1rem 1.25rem' },
  viewerPre:     { margin:0, fontFamily:'monospace', fontSize:'0.8rem', color:'#94a3b8', whiteSpace:'pre-wrap', wordBreak:'break-word', lineHeight:1.6 },
  viewerEditArea:{ width:'100%', background:'#0a1220', border:'1px solid #1e293b', borderRadius:'6px', color:'#cbd5e1', fontSize:'0.8rem', lineHeight:1.6, padding:'0.6rem', resize:'vertical', outline:'none', fontFamily:'monospace', boxSizing:'border-box', minHeight:'300px' },
  versionItem:   { display:'flex', alignItems:'center', gap:'0.5rem', padding:'0.5rem 0.6rem', borderRadius:'6px', marginBottom:'4px', border:'1px solid #1e293b', background:'#0a1220', fontSize:'0.78rem' },
  versionMeta:   { flex:1, minWidth:0 },
  versionNum:    { color:'#cbd5e1', fontWeight:600 },
  versionDate:   { color:'#475569', fontSize:'0.7rem', marginTop:'1px' },
  restoreBtn:    { padding:'0.15rem 0.5rem', borderRadius:'4px', border:'1px solid #1e4e3a', background:'#0f4c3a', color:'#34d399', cursor:'pointer', fontSize:'0.72rem', whiteSpace:'nowrap' },
  renameInput:   { flex:1, padding:'0.15rem 0.4rem', borderRadius:'4px', border:'1px solid #6366f1', background:'#0f172a', color:'#e2e8f0', fontSize:'0.78rem', outline:'none' },
  toolPill:    { display:'inline-flex', alignItems:'center', gap:'4px', fontSize:'0.72rem', color:'#94a3b8', background:'#0f172a', border:'1px solid #1e293b', borderRadius:'6px', padding:'2px 8px', marginBottom:'4px', cursor:'pointer' },
  toolResult:  { fontSize:'0.72rem', color:'#64748b', background:'#0f172a', borderRadius:'4px', padding:'6px 8px', marginBottom:'6px', whiteSpace:'pre-wrap', wordBreak:'break-word', maxHeight:'120px', overflowY:'auto' },
  text:        { margin:0, whiteSpace:'pre-wrap', wordBreak:'break-word' },
  cursor:      { display:'inline-block', width:'2px', height:'1em', background:'#94a3b8', marginLeft:'2px', verticalAlign:'text-bottom', animation:'blink 1s step-end infinite' },
  tag:         { display:'block', marginTop:'0.35rem', fontSize:'0.7rem', color:'#64748b' },

  // compare
  compareRow:  { display:'flex', gap:'0.75rem', alignSelf:'stretch' },
  compareCard: { flex:1, minWidth:0, background:'#1e293b', border:'1px solid #334155', borderRadius:'12px', padding:'0.75rem 1rem' },
  cardHeader:  { fontSize:'0.7rem', color:'#64748b', marginBottom:'0.5rem', fontWeight:600, letterSpacing:'0.04em' },
  cardModel:   { fontSize:'0.65rem', color:'#475569', marginTop:'0.35rem' },

  // toolbar
  toolbarWrap: { background:'#1e293b', borderTop:'1px solid #1e293b', padding:'0.5rem 1.5rem 0' },
  toolbar:     { display:'flex', justifyContent:'space-between', alignItems:'center', gap:'0.5rem' },
  modelPills:  { display:'flex', gap:'0.25rem', flexWrap:'wrap' },
  pill:        { padding:'0.25rem 0.65rem', borderRadius:'20px', border:'1px solid #334155', background:'none', color:'#64748b', cursor:'pointer', fontSize:'0.75rem', transition:'all 0.12s' },
  pillActive:  { background:'#6366f1', borderColor:'#6366f1', color:'#fff' },
  pillCompare: { background:'#0f4c3a', borderColor:'#34d399', color:'#34d399' },
  toolRight:   { display:'flex', gap:'0.25rem' },

  // params expander
  paramsBar:   { display:'flex', gap:'1.5rem', padding:'0.5rem 0', marginTop:'0.35rem', borderTop:'1px solid #1e293b' },
  paramItem:   { display:'flex', alignItems:'center', gap:'0.4rem', flex:1, minWidth:0 },
  paramLabel:  { fontSize:'0.7rem', minWidth:'34px', flexShrink:0 },
  paramVal:    { fontSize:'0.7rem', minWidth:'36px', textAlign:'right', flexShrink:0 },

  // input bar
  bar:         { display:'flex', gap:'0.6rem', padding:'0.75rem 1.5rem 1rem', background:'#1e293b' },
  input:       { flex:1, padding:'0.7rem 1rem', borderRadius:'8px', border:'1px solid #334155', background:'#0f172a', color:'#f1f5f9', fontSize:'1rem', outline:'none' },
  send:        { padding:'0.7rem 1.2rem', borderRadius:'8px', background:'#6366f1', color:'#fff', border:'none', cursor:'pointer', fontWeight:600, fontSize:'0.95rem' },

  // overlay + panels
  overlay:     { position:'absolute', inset:0, background:'rgba(0,0,0,0.45)', zIndex:10 },
  memPanel:    { position:'absolute', top:0, right:0, bottom:0, width:'380px', maxWidth:'90vw', background:'#0f172a', borderLeft:'1px solid #1e293b', zIndex:11, display:'flex', flexDirection:'column', transition:'transform 0.28s cubic-bezier(.4,0,.2,1)' },
  memHeader:   { padding:'1rem 1.25rem 0.75rem', borderBottom:'1px solid #1e293b', flexShrink:0 },
  memTitleRow: { display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'0.25rem' },
  memTitle:    { fontWeight:700, fontSize:'0.95rem', color:'#e2e8f0', display:'flex', alignItems:'center', gap:'0.5rem' },
  memMeta:     { fontSize:'0.7rem', color:'#475569' },
  memHdrBtns:  { display:'flex', gap:'0.4rem', alignItems:'center' },
  refreshBtn:  { background:'none', border:'1px solid #1e293b', color:'#64748b', cursor:'pointer', fontSize:'0.75rem', padding:'0.2rem 0.5rem', borderRadius:'4px' },
  closeBtn:    { background:'none', border:'none', color:'#64748b', cursor:'pointer', fontSize:'1.1rem', padding:'0.25rem', lineHeight:1 },
  tabBar:      { display:'flex', borderBottom:'1px solid #1e293b', flexShrink:0 },
  tabBtn:      { flex:1, padding:'0.5rem', background:'none', border:'none', cursor:'pointer', fontSize:'0.78rem', color:'#475569', borderBottom:'2px solid transparent' },
  tabActive:   { color:'#818cf8', borderBottomColor:'#818cf8' },
  memBody:     { flex:1, overflowY:'auto', padding:'1rem 1.25rem' },
  emptyMem:    { color:'#475569', fontSize:'0.85rem', textAlign:'center', marginTop:'3rem' },
  section:     { marginBottom:'1.25rem' },
  secLabel:    { fontSize:'0.7rem', fontWeight:700, letterSpacing:'0.08em', marginBottom:'0.4rem', padding:'0.2rem 0.5rem', borderRadius:'4px', display:'inline-block' },
  kv:          { display:'flex', gap:'0.5rem', fontSize:'0.82rem', lineHeight:1.5, padding:'0.15rem 0', borderBottom:'1px solid #1e293b' },
  kvKey:       { color:'#64748b', minWidth:'90px', flexShrink:0 },
  kvVal:       { color:'#cbd5e1', wordBreak:'break-word', flex:1 },
  divider:     { borderTop:'1px solid #1e293b', margin:'1rem 0 0.75rem', display:'flex', alignItems:'center', gap:'0.5rem' },
  divLabel:    { fontSize:'0.65rem', fontWeight:700, letterSpacing:'0.1em', color:'#334155', whiteSpace:'nowrap' },
  memFooter:   { padding:'0.75rem 1.25rem', borderTop:'1px solid #1e293b', flexShrink:0, display:'flex', flexDirection:'column', gap:'0.5rem' },
  footerRow:   { display:'flex', justifyContent:'space-between', alignItems:'center' },
  footerActions: { display:'flex', gap:'0.4rem' },
  actionBtn:   { background:'none', border:'1px solid #1e293b', color:'#64748b', cursor:'pointer', fontSize:'0.72rem', padding:'0.2rem 0.5rem', borderRadius:'4px' },
  footerStats: { fontSize:'0.7rem', color:'#334155' },
  memToggleRow:   { display:'flex', alignItems:'center', justifyContent:'space-between', paddingTop:'0.35rem', borderTop:'1px solid #0f172a' },
  memToggleLabel: { fontSize:'0.72rem', color:'#475569' },
  togglePill:     { display:'flex', alignItems:'center', gap:'0.35rem', background:'none', border:'1px solid #334155', borderRadius:'12px', padding:'0.2rem 0.6rem', cursor:'pointer', fontSize:'0.72rem' },
  editArea:    { width:'100%', background:'#0a1220', border:'1px solid #1e293b', borderRadius:'6px', color:'#cbd5e1', fontSize:'0.8rem', lineHeight:1.6, padding:'0.6rem', resize:'vertical', outline:'none', fontFamily:'monospace', boxSizing:'border-box' },
  editLabel:   { fontSize:'0.7rem', color:'#475569', marginBottom:'0.3rem', marginTop:'0.75rem' },
  editBtns:    { display:'flex', gap:'0.5rem', marginTop:'1rem' },
  saveBtn:     { padding:'0.4rem 1rem', borderRadius:'6px', background:'#6366f1', color:'#fff', border:'none', cursor:'pointer', fontSize:'0.82rem', fontWeight:600 },
  cancelBtn:   { padding:'0.4rem 0.75rem', borderRadius:'6px', background:'none', color:'#64748b', border:'1px solid #334155', cursor:'pointer', fontSize:'0.82rem' },
  historyList: { display:'flex', flexDirection:'column', gap:'0.5rem' },
  historyItem: { padding:'0.5rem 0.75rem', borderRadius:'6px', border:'1px solid #1e293b', cursor:'pointer', fontSize:'0.8rem', background:'#0a1220' },
  historyMeta: { color:'#475569', fontSize:'0.7rem', marginTop:'0.2rem' },
  diffBox:     { marginTop:'1rem', padding:'0.75rem', background:'#0a1220', borderRadius:'6px', border:'1px solid #1e293b' },
  diffTitle:   { fontSize:'0.7rem', color:'#64748b', marginBottom:'0.5rem', fontWeight:600 },
  diffLine:    { fontSize:'0.78rem', lineHeight:1.6, padding:'0.05rem 0.4rem', borderRadius:'3px', marginBottom:'1px', fontFamily:'monospace', wordBreak:'break-word' },
  diffAdded:   { background:'rgba(52,211,153,0.12)', color:'#34d399' },
  diffRemoved: { background:'rgba(248,113,113,0.12)', color:'#f87171' },
  diffSame:    { color:'#475569' },
  updatingDot: { width:'6px', height:'6px', borderRadius:'50%', background:'#34d399', animation:'pulse 1s ease-in-out infinite' },
  flashBody:   { animation:'memFlash 1.5s ease-out' },

  // settings modal
  settingsModal:  { position:'absolute', top:'50%', left:'50%', transform:'translate(-50%,-50%)', width:'440px', maxWidth:'92vw', background:'#0f172a', border:'1px solid #1e293b', borderRadius:'12px', zIndex:20, display:'flex', flexDirection:'column' },
  settingsHeader: { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'1rem 1.25rem', borderBottom:'1px solid #1e293b' },
  settingsTitle:  { fontWeight:700, fontSize:'0.9rem', color:'#e2e8f0' },
  settingsBody:   { padding:'1.25rem', overflowY:'auto' },
  settingsFooter: { display:'flex', justifyContent:'flex-end', gap:'0.5rem', padding:'0.75rem 1.25rem', borderTop:'1px solid #1e293b' },

  // ask_user card
  askCard:       { display:'flex', gap:'0.6rem', alignItems:'flex-start', background:'rgba(251,191,36,0.08)', border:'1px solid rgba(251,191,36,0.25)', borderRadius:'8px', padding:'0.65rem 0.85rem', marginTop:'0.5rem' },
  askIcon:       { fontSize:'1rem', flexShrink:0, marginTop:'1px' },
  askLabel:      { fontSize:'0.7rem', color:'#fbbf24', fontWeight:600, marginBottom:'0.2rem', letterSpacing:'0.04em' },
  askQuestion:   { fontSize:'0.85rem', color:'#fde68a', lineHeight:1.5 },

  // tool log panel
  toolLogPanel:  { position:'absolute', top:0, right:0, bottom:0, width:'480px', maxWidth:'95vw', background:'#0f172a', borderLeft:'1px solid #1e293b', zIndex:11, display:'flex', flexDirection:'column', transition:'transform 0.28s cubic-bezier(.4,0,.2,1)' },
  toolLogHdr:    { padding:'1rem 1.25rem 0.75rem', borderBottom:'1px solid #1e293b', flexShrink:0, display:'flex', justifyContent:'space-between', alignItems:'center' },
  toolLogTitle:  { fontWeight:700, fontSize:'0.95rem', color:'#e2e8f0' },
  toolLogBody:   { flex:1, overflowY:'auto', padding:'0.75rem 1.25rem' },
  toolLogRow:    { display:'flex', flexDirection:'column', gap:'2px', padding:'0.5rem 0.6rem', borderRadius:'6px', marginBottom:'4px', border:'1px solid #1e293b', background:'#0a1220', fontSize:'0.78rem' },
  toolLogMeta:   { display:'flex', gap:'0.5rem', alignItems:'center' },
  toolLogName:   { color:'#818cf8', fontWeight:600, fontSize:'0.75rem' },
  toolLogTime:   { color:'#475569', fontSize:'0.7rem' },
  toolLogArgs:   { color:'#64748b', fontSize:'0.7rem', fontFamily:'monospace', whiteSpace:'pre-wrap', wordBreak:'break-all', maxHeight:'48px', overflow:'hidden' },
  toolLogResult: { color:'#94a3b8', fontSize:'0.72rem', whiteSpace:'pre-wrap', wordBreak:'break-word', maxHeight:'60px', overflow:'hidden' },

  // files panel
  filePanel:     { position:'absolute', top:0, right:0, bottom:0, width:'400px', maxWidth:'92vw', background:'#0f172a', borderLeft:'1px solid #1e293b', zIndex:11, display:'flex', flexDirection:'column', transition:'transform 0.28s cubic-bezier(.4,0,.2,1)' },
  filePanelHdr:  { padding:'1rem 1.25rem 0.75rem', borderBottom:'1px solid #1e293b', flexShrink:0 },
  fileTitleRow:  { display:'flex', justifyContent:'space-between', alignItems:'center' },
  fileTitle:     { fontWeight:700, fontSize:'0.95rem', color:'#e2e8f0' },
  fileUploadRow: { display:'flex', gap:'0.4rem', padding:'0.75rem 1.25rem', borderBottom:'1px solid #1e293b', flexShrink:0, flexWrap:'wrap' },
  urlRow:        { display:'flex', gap:'0.4rem', padding:'0 1.25rem 0.75rem', borderBottom:'1px solid #1e293b', flexShrink:0 },
  urlInput:      { flex:1, padding:'0.3rem 0.6rem', borderRadius:'6px', border:'1px solid #334155', background:'#0f172a', color:'#f1f5f9', fontSize:'0.78rem', outline:'none' },
  ingestBtn:     { padding:'0.3rem 0.75rem', borderRadius:'6px', background:'#0f4c3a', color:'#34d399', border:'1px solid #1e4e3a', cursor:'pointer', fontSize:'0.75rem', fontWeight:600, whiteSpace:'nowrap' },
  wsRow:         { display:'flex', gap:'0.3rem', padding:'0.5rem 1.25rem', borderBottom:'1px solid #1e293b', flexShrink:0, flexWrap:'wrap', alignItems:'center' },
  wsLabel:       { fontSize:'0.7rem', color:'#475569', marginRight:'0.15rem' },
  wsPill:        { padding:'0.15rem 0.5rem', borderRadius:'12px', border:'1px solid #334155', background:'none', color:'#64748b', cursor:'pointer', fontSize:'0.7rem' },
  wsPillActive:  { background:'#1e293b', borderColor:'#6366f1', color:'#818cf8' },
  fileList:      { flex:1, overflowY:'auto', padding:'0.5rem 1.25rem' },
  fileItem:      { display:'flex', alignItems:'center', gap:'0.5rem', padding:'0.5rem 0.6rem', borderRadius:'6px', marginBottom:'4px', border:'1px solid #1e293b', background:'#0a1220' },
  fileName:      { flex:1, minWidth:0, fontSize:'0.78rem', color:'#cbd5e1', whiteSpace:'nowrap', overflow:'hidden', textOverflow:'ellipsis' },
  fileMeta:      { fontSize:'0.65rem', color:'#475569', whiteSpace:'nowrap' },
  statusBadge:   { fontSize:'0.62rem', padding:'0.1rem 0.35rem', borderRadius:'4px', fontWeight:600, whiteSpace:'nowrap' },
  attachBtn:     { padding:'0.15rem 0.4rem', borderRadius:'4px', border:'1px solid #334155', background:'none', cursor:'pointer', fontSize:'0.7rem', color:'#64748b', whiteSpace:'nowrap' },
  attachedBtn:   { background:'#1e293b', borderColor:'#6366f1', color:'#818cf8' },
  delBtn:        { padding:'0.15rem 0.3rem', borderRadius:'4px', border:'1px solid #334155', background:'none', cursor:'pointer', fontSize:'0.7rem', color:'#ef4444' },
  fileChipsRow:  { display:'flex', gap:'0.35rem', padding:'0 1.5rem 0.35rem', flexWrap:'wrap' },
  fileChip:      { display:'flex', alignItems:'center', gap:'0.3rem', padding:'0.2rem 0.5rem', borderRadius:'12px', background:'#1e293b', border:'1px solid #334155', fontSize:'0.72rem', color:'#818cf8' },
  chipX:         { cursor:'pointer', color:'#475569', fontSize:'0.8rem', lineHeight:1 },

  // workspace modal / gear
  wsGearBtn:    { background:'none', border:'none', color:'#475569', cursor:'pointer', fontSize:'0.6rem', padding:'0 1px', lineHeight:1, marginLeft:'1px' },
  wsPlusBtn:    { padding:'0.15rem 0.45rem', borderRadius:'12px', border:'1px dashed #334155', background:'none', color:'#475569', cursor:'pointer', fontSize:'0.7rem', lineHeight:1.2 },
  wsModal:      { position:'absolute', top:'50%', left:'50%', transform:'translate(-50%,-50%)', width:'420px', maxWidth:'92vw', background:'#0f172a', border:'1px solid #1e293b', borderRadius:'12px', zIndex:22, display:'flex', flexDirection:'column' },

  // sidebar search
  sideSearchWrap:  { padding:'0.4rem 0.5rem', borderBottom:'1px solid #1e293b', flexShrink:0 },
  sideSearchInput: { width:'100%', padding:'0.35rem 0.6rem', borderRadius:'6px', border:'1px solid #1e293b', background:'#0a1220', color:'#f1f5f9', fontSize:'0.78rem', outline:'none', boxSizing:'border-box' },

  // invite panel
  invitePanel:  { position:'absolute', top:0, right:0, bottom:0, width:'420px', maxWidth:'95vw', background:'#0f172a', borderLeft:'1px solid #1e293b', zIndex:11, display:'flex', flexDirection:'column', transition:'transform 0.28s cubic-bezier(.4,0,.2,1)' },
  inviteHdr:    { padding:'1rem 1.25rem 0.75rem', borderBottom:'1px solid #1e293b', flexShrink:0, display:'flex', justifyContent:'space-between', alignItems:'center' },
  inviteTitle:  { fontWeight:700, fontSize:'0.95rem', color:'#e2e8f0' },
  inviteBody:   { flex:1, overflowY:'auto', padding:'1rem 1.25rem' },
  inviteRow:    { padding:'0.6rem 0.75rem', borderRadius:'6px', marginBottom:'6px', border:'1px solid #1e293b', background:'#0a1220', fontSize:'0.78rem' },
  tokenBox:     { background:'rgba(99,102,241,0.08)', border:'1px solid rgba(99,102,241,0.25)', borderRadius:'8px', padding:'0.75rem', marginBottom:'1rem' },
  tokenText:    { fontFamily:'monospace', fontSize:'0.72rem', color:'#818cf8', wordBreak:'break-all', cursor:'pointer', userSelect:'all' },

  // proactive card
  proactiveCard: { display:'flex', gap:'0.6rem', alignItems:'flex-start', background:'rgba(99,102,241,0.08)', border:'1px solid rgba(99,102,241,0.3)', borderRadius:'8px', padding:'0.65rem 0.85rem', margin:'0 1.5rem 0.5rem' },
  proactiveLabel:{ fontSize:'0.7rem', color:'#818cf8', fontWeight:600, marginBottom:'0.2rem', letterSpacing:'0.04em' },
  proactiveTxt:  { fontSize:'0.85rem', color:'#c7d2fe', lineHeight:1.5, flex:1 },
  proactiveDismiss: { background:'none', border:'none', color:'#475569', cursor:'pointer', fontSize:'0.9rem', padding:'0 2px', lineHeight:1, flexShrink:0 },

  // insights panel
  insightsPanel: { position:'absolute', top:0, right:0, bottom:0, width:'400px', maxWidth:'92vw', background:'#0f172a', borderLeft:'1px solid #1e293b', zIndex:11, display:'flex', flexDirection:'column', transition:'transform 0.28s cubic-bezier(.4,0,.2,1)' },
  insightsHdr:   { padding:'1rem 1.25rem 0.75rem', borderBottom:'1px solid #1e293b', flexShrink:0, display:'flex', justifyContent:'space-between', alignItems:'center' },
  insightsTitle: { fontWeight:700, fontSize:'0.95rem', color:'#e2e8f0' },
  insightsBody:  { flex:1, overflowY:'auto', padding:'1rem 1.25rem' },
  insightRow:    { display:'flex', gap:'0.5rem', alignItems:'flex-start', padding:'0.65rem 0.75rem', borderRadius:'8px', marginBottom:'6px', border:'1px solid #1e293b', background:'#0a1220', fontSize:'0.82rem', cursor:'pointer', transition:'border-color 0.15s' },
  insightDot:    { width:'7px', height:'7px', borderRadius:'50%', background:'#818cf8', flexShrink:0, marginTop:'5px' },
  insightContent:{ flex:1, color:'#cbd5e1', lineHeight:1.5 },
  insightMeta:   { fontSize:'0.68rem', color:'#475569', marginTop:'0.25rem' },
  insightDel:    { background:'none', border:'none', color:'#475569', cursor:'pointer', fontSize:'0.8rem', padding:'2px 4px', borderRadius:'4px', flexShrink:0, lineHeight:1 },
  unreadBadge:   { display:'inline-flex', alignItems:'center', justifyContent:'center', minWidth:'16px', height:'16px', borderRadius:'8px', background:'#818cf8', color:'#fff', fontSize:'0.62rem', fontWeight:700, padding:'0 3px', marginLeft:'3px' },

  // token meta + usage panel
  tokMeta:       { display:'block', marginTop:'0.3rem', fontSize:'0.68rem', color:'#334155', fontFamily:'monospace' },
  usagePanel:    { position:'absolute', top:0, right:0, bottom:0, width:'340px', maxWidth:'92vw', background:'#0f172a', borderLeft:'1px solid #1e293b', zIndex:11, display:'flex', flexDirection:'column', transition:'transform 0.28s cubic-bezier(.4,0,.2,1)' },
  usageHdr:      { padding:'1rem 1.25rem 0.75rem', borderBottom:'1px solid #1e293b', flexShrink:0, display:'flex', justifyContent:'space-between', alignItems:'center' },
  usageTitle:    { fontWeight:700, fontSize:'0.95rem', color:'#e2e8f0' },
  usageBody:     { flex:1, overflowY:'auto', padding:'1rem 1.25rem' },
  usageStat:     { display:'flex', justifyContent:'space-between', alignItems:'center', padding:'0.5rem 0', borderBottom:'1px solid #1e293b', fontSize:'0.82rem' },
  usageKey:      { color:'#64748b' },
  usageVal:      { color:'#e2e8f0', fontFamily:'monospace', fontWeight:600 },
}

export default s
